[package]
name = "tg-kit-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
grammers-client.workspace = true
linkme.workspace = true
tokio.workspace = true